version: 1
disable_existing_loggers: false
formatters:
  standard:
    format: '%(asctime)s - %(app_name)s - %(component)s - %(levelname)s - %(message)s'
handlers:
  default:
    level: INFO
    class: logging.StreamHandler
    formatter: standard
loggers:
  '':
    handlers: [default]
    level: INFO
    propagate: true
